### ISSUE TITLE
Initialisation flexibility and offline usage

### ISSUE THREAD

**Issue by dmos62** [wnabil/ngx-drupal7-services#1]
When launching the app, if this module fails to connect to the backend (due to network problems or the backend being down temporarily), the whole app crashes. This is due to tight coupling between app's initialisation and ngx-drupal7-services' initialisation, which in this case is doing a `system/connect` HTTP call. If you disable the [module import hook](https://github.com/wnabil/ngx-drupal7-services/blob/master/src/index.ts#L52), the app launches fine and you can initialise at will.

**Comment by wnabil** [comment]
Hi, sorry for late.
Removing the initialization will break almost 90% of the functionality of the online flow.
As a user who will connect to Drupal backend you must have a connection even if the user was anonymous.
For example if you logged in and refreshed the page, if we didn't request the connect API the user will appears as he logged out, also when he try to login the backend will response with error that the user is already logged in or invalid token.
I will handle this issue on the next few days, Thank you for helping.
