### ISSUE TITLE
 XMLHttpRequest Issue

### ISSUE THREAD

**Issue by hanishkeloth** [wnabil/ngx-drupal7-services#17]
Connecting with localhost works fine.Live server getting following error.
Access to XMLHttpRequest at 'https://**.com/services/session/token' from origin 'http://localhost:4200' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: Redirect is not allowed for a preflight request.

**Comment by wnabil** [comment]
Hi, the issue is not related to the package itself, this issue is a CORS issue
However, in readme file there is an instructions to configure your nginx server and CORS drupal module
please see: https://github.com/wnabil/ngx-drupal7-services#setup-for-cors
