### ISSUE TITLE
First execution on iOS 11 w/ Cordova fails to maintain sessions

### ISSUE THREAD

**Issue by centogram** [wnabil/ngx-drupal7-services#21]
This is an Ionic 4.2 / Angular 7.2 app and the issue we have is that systemService.connect always returns an anonymous user for iOS Device or Simulator.  Browser/Android no issue.  I wrongly assumed that sessid/tokens were not being stored properaly with localStorage.  That is not the case.

```
userService.login() : Successful login
(then Immediately)
systemService.connect() : Anonymous w/ uid:0
```

**Comment by centogram** [comment]
Here is an example using Ionic Storage

```
import { Storage } from '@ionic/storage';

...

export class AppModule {
  constructor(
    private storage: Storage
  ) {
    const drupalSettings: Settings = {
      apiProtocol: 'https',
      apiHost: environment.apiHost,
      apiEndPoint: 'api',
      language: 'und',
      requestTimeout: environment.requestTimeout,
      localStorage: {
        setItem: (key, value) => {
          storage.set(key, value);
        },
        getItem: async (key) => {  
          let value = await storage.get(key);
          return value;
        },
        clear: () => {
          storage.clear();
        }
      },
    };
    DrupalConstants.Settings = drupalSettings;
  }
}
```

**Comment by centogram** [comment]
Ok, forgive me for flooding your queues.  Now that some feedback from the field is back this does not solve our problem.  I'll rescind the pull request.  

**Perhaps you can offer some advice otherwise:**   

This is an Ionic 4.2 / Angular 7.2 app and the issue we have is that systemService.connect always returns an anonymous user for iOS Device or Simulator.  Browser/Android no issue.  I wrongly assumed that sessid/tokens were not being stored properaly with localStorage.  That is not the case.

```
userService.login() : Successful login
(then Immediately)
systemService.connect() : Anonymous w/ uid:0
```

**Comment by centogram** [comment]
Another followup.  Closing and restarting the app on iOS seems to resolve everything.  I think the problem may be related to this specific issue: https://github.com/ionic-team/cordova-plugin-ionic-webview/issues/22

> When installing a fresh build of my application and attempting to log in, it fails because the authentication cookie sent by the server is never stored. Closing the application and re-launching fixes the issue. There is an identical issue for cordova-plugin-wkwebview-engine here. Is this one of the issues that has been / will be fixed in this fork, or is there a viable workaround at this time?

Also :

> This also causes websockets to break on many apps that rely on sticky session cookies to connect to the same server. Even if you were to use localstorage for auth, it's hard to get around the sticky session issue.

Can you think of a way around this?

**Comment by wnabil** [comment]
Hi @centogram ,
I got this issue for almost 1 year ago and the great news that i managed to solve this 5 days ago.
The problem is there is a bug with WKWebView that did not sync the cookies at first app launch.

For more info about this problem check this issue [here](https://github.com/ionic-team/cordova-plugin-ionic-webview/issues/22)

However the solution is here in this comment using https://github.com/CWBudde/cordova-plugin-wkwebview-inject-cookie

https://github.com/ionic-team/cordova-plugin-ionic-webview/issues/22#issuecomment-398036017

```
npm i cordova-plugin-wkwebview-inject-cookie
ionic cordova plugin add cordova-plugin-wkwebview-inject-cookie
```

app.component.ts
```javascript
declare var wkWebView: any;

...

    document.addEventListener('deviceready', () => {
      wkWebView.injectCookie('https://domain.com/');
    });
```

**Comment by centogram** [comment]
Thanks for the suggestion.  I was really scratching my head to solve this.   I'll give this a try.  

**Question**
_Are you adding the eventListener to the constructor, ngOnInit or outside the Component class altogether?_

**Comment by wnabil** [comment]
No in ionic its directly inside device ready event so no need for event listener
-previous comment updated

This is exactly how you implement it in ionic

```javascript
this.platform.ready().then(() => {
... // the rest of init commands
      if (this.platform.is('ios')) {
        wkWebView.injectCookie(DrupalConstants.backEndUrl);
      }
});
```
