### ISSUE TITLE
Field label and Value distorted

### ISSUE THREAD

**Issue by Beniyoo** [wnabil/ngx-drupal7-services#30]
The fields label, value even the number of fields is not what it should be. The format_output to 1 gives a correct answer(the same as the preview in views), but the format_output 0 gives completely different and incorrect output.This is using both **_filters_** and **_args_** in ViewOptions.
_**From:**_
```array (
  0 => 
  stdClass::__set_state(array(
     'nid' => '...',
     'field_material_image' => 
    array (
    ),
     'title' => 'OPC',
     'field_price' => '...',
     'field_material_type' => 'Cement',
  )),
  1 => ...
```
**_in Views_** and using **_format_output 1_**
_**to:**_

`0: {nid: "Cement", node_title: "OPC"}...`

**_using format_output 0_**

**Comment by wnabil** [comment]
Hi, this library doesn't use the format output to be set as 1, the default is always 0 so the exported data is always json and we can parse it in angular easy without any custom tools, if you want it to be a custom output then set the flag for format_output 1 and your view will always export the data in array of strings and you can handle the interface by overriding it in your subscription.
in fact i do not know what the point of using themed view in services but anyways u still can use it.
with format_output: 
![image](https://user-images.githubusercontent.com/23165327/60385296-f731a880-9a87-11e9-9f40-807adfa739a4.png)

without: "simply json"
![image](https://user-images.githubusercontent.com/23165327/60385321-365ff980-9a88-11e9-83af-ca62dd79746e.png)

**Comment by Beniyoo** [comment]
I Checked with other views the response is the same. Your example is what i was expecting but the response without format is still distorted in my views, is there any thing i am missing you can think of?

**Comment by wnabil** [comment]
make sure you enabled json format in your endpoint as described in readme file
https://github.com/wnabil/ngx-drupal7-services#setup-for-drupal

![image](https://user-images.githubusercontent.com/23165327/60386562-b9884c00-9a96-11e9-98c5-3341bb2497c6.png)

**Comment by wnabil** [comment]
Any news ? please close the issue if its not related
