### ISSUE TITLE
Exposed filters not working

### ISSUE THREAD

**Issue by Beniyoo** [wnabil/ngx-drupal7-services#31]
I am using views to filter(combine filter), but the filters parameters are not recognized at all. It sends back the unfiltered results. i have seen the generated url it is as expected(... &filters[combine_search]=Sand& ...) but is ignored.

**Comment by Beniyoo** [comment]
solved with adding the following code:

` let filters = '&';
    if (options['filters'] instanceof Object) {
      Object.keys(options['filters']).forEach((element: string, index) => {
        filters += `${element}=${options['filters'][element]}&`;
      });
    }
    return this.get(servicePath + args + filters);`

the above code changed the filters from **&filters[key]=value&** format to **&key=value&**

**Comment by wnabil** [comment]
Hello, can you please send me the version of Drupal modules (services, views, services_views)
