### ISSUE TITLE
Want to use Services display in a view

### ISSUE THREAD

**Issue by Beniyoo** [wnabil/ngx-drupal7-services#4]
As i understand it the views resource use the views resource to retrieve from a view in drupal 7. But the output is different with services display. I have been using the services display to get the data as i wanted it, but views is only implemented using the views resource. If there is a views resource that can implement services display or all together a resource that uses path input to retrieve will be helpful.
Trying to use:
http://example.com/endpoint_path/resource_name
to retrieve data from a view

**Comment by wnabil** [comment]
The views service retrieves the data from the services views module which takes the view machine name by default not the view path url and it is already supports the multiple displays:

    const options: ViewOptions = {
      display_id: 'service_1', // this is your display id
    }
    this.viewService.getView("my_view_machine_name", options).subscribe(data => {
      // console.log(data);
    });

the above code will request the backend url as `http://example.com/endpoint_path/views/view_machine_name?display_id=services_1`

If you really need to request the view path without using views services module so you should create your custom service by inheriting the main service and setting the entityType property to an empty string and implement the resources inside your custom service
You will never need it if your resources is a view and you can get multiple displays by setting the display_id in the view options but custom service will help you if you have a custom module that implements a custom resources
Please note that services views module now made the display_id option required and if you sent the request without setting it, the response will be 404

**Comment by Beniyoo** [comment]
Thanks for the quick response. I have made another class extending MainService and works as expected.

@Injectable()
export class ViewService2 extends MainService {
  entityType = '';

  /**
   * impelemnt retrive resource
   * @param servicePath service Display Path
   * @param options parameters of filteration for this view
   * @return array of view rows OR view html code if the options format_output is 1
   */
  getView(servicePath: string, options?: ViewOptions): Observable<any[]> {
    const args = this.getArgs(options);
    return this.get(servicePath + args);
  }

}

and calling with no options,

this.viewService2.getView("path of services view display").subscribe(result => {
// use result
});
