### ISSUE TITLE
CORS issues

### ISSUE THREAD

**Issue by Beniyoo** [wnabil/ngx-drupal7-services#6]
I ran into a problem into CORS issues and the only solutions i can find is to add 'Access-Control-Allow-Origin' header in all requests. My application works in browsers with CORS plugins but not on device tests.

**Comment by wnabil** [comment]
You do not need to send anything from your front-end app.
Look at the readme file please there is already a tutorial how to configure CORS module and make sure your webserver have no CORS rules
