### ISSUE TITLE
filters object with string values are exploded

### ISSUE THREAD

**Issue by mohamed-nabawy** [wnabil/ngx-drupal7-services#8]
there is a bug in filters that when i pass an object with a string value for a key filter(name)
i.e.
let vo ={
filters:{
        name:"amaz"
}
}
passed in the View Options argument, the url query string that is constructed to execute the view is like this:
?display_id=services_1&filters[name][0]=a&filters[name][1]=m&filters[name][2]=a&filters[name][3]=z&

and the bug i think is causing this is in "main.service.ts" file , "optionToString" method at lines 327,329 
329: if (value instanceof Object) is always true if 327 else if (value instanceof Object) is satisfied.

**Comment by wnabil** [comment]
Hi, thanks for the help
Yes i confirm there is an issue with the filters for this case.
I have tested the PR #10 but it seems doesn't fix the problem, please update it with a correct fix or create a new PR and close this one.
